jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm i web-push node-fetch

      - name: Send push
        run: node scripts/send-push.js
        env:
          VAPID_PUBLIC: ${{ secrets.VAPID_PUBLIC }}
          VAPID_PRIVATE: ${{ secrets.VAPID_PRIVATE }}
          WORKER_URL: ${{ secrets.WORKER_URL }}
